name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Codegen check
        run: |
          if [[ $(git --no-pager diff -- . ) ]]; then
            echo "Codegen output does not match checked-in files"
            git --no-pager diff -- .
            exit 1
          fi

      - name: Lint
        run: yarn lint
